{% set name = "pyinstrument_cext" %}
{% set version = "0.1.6" %}
{% set sha256 = "fbfa21ced94d64dd468712ae3323c51bf57eda5f3354f5f7f9db713d66d99265" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyinstrument_cext

about:
  home: https://github.com/joerick/pyinstrument_cext
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A CPython extension supporting pyinstrument'
  description: 'A CPython extension supporting pyinstrument'
  dev_url: https://github.com/joerick/pyinstrument_cext

extra:
  recipe-maintainers:
    - moorepants
